### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by mchambaud** [AngularClass/angular-universal-transfer-state#2]
What is this for? Why do I need this? 

I see that people using universal have some sort of transfer-state module to go from client to server... but why do I need this? What does it do? 

I'm currently having an issue with ngx-translate where the translation is done on the server but when the client kicks in it translates again which causes a flickr, I'm guessing it's because I do not have a state transfer module but even after using this it still occurs..

**Comment by m98** [comment]
This repo was helpful when there was no official API for transfer state on Angular, but from Angular version 5 you can use [TransferState](https://angular.io/api/platform-browser/TransferState) API.

**Comment by mchambaud** [comment]
Yup, this makes complet sense since Angular 5. We can close this now!
